# Filename: cloudbuild.yaml

steps:
  # ... (steps 1 through 7 are the same) ...

  # 7. Apply Terraform configuration
  - name: 'hashicorp/terraform:1.5.7'
    id: "Terraform apply"
    entrypoint: 'terraform'
    args: ['apply', '-auto-approve', '-var', 'project_id=${PROJECT_ID}']
    waitFor: ["Terraform init", "Push retrieval-service", "Push frontend-service"]

  # 8. Run Database Migrations
  - name: 'gcr.io/cloud-builders/gcloud'
    id: "Run Database Migrations"
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y python3 python3-pip
        pip3 install -r src/retrieval_service/requirements.txt

        # --- THIS IS THE FIX ---
        # First, delete any old, cached version of the proxy file
        rm -f cloud-sql-proxy
        # --- END FIX ---

        # Now, download the fresh, correct version
        curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-proxy/v2.8.2/cloud-sql-proxy.linux.amd64
        
        chmod +x cloud-sql-proxy
        chmod +x ./scripts/run_migrations.sh
        ./scripts/run_migrations.sh
    env:
      - 'DB_USER=${_DB_USER}'
      - 'DB_PASSWORD=${_DB_PASS}'
      - 'DB_NAME=${_DB_NAME}'
      - 'DB_INSTANCE=${_DB_INSTANCE}'
      - 'DB_PROJECT=${PROJECT_ID}'
      - 'DB_REGION=${_REGION}'
    waitFor: ["Terraform apply"]

# ... (rest of the file is the same) ...