steps:
# Step 1: Build the BACKEND Docker image
- name: 'gcr.io/kaniko-project/executor:latest'
  id: 'build-backend'
  args:
  - --dockerfile=src/retrieval_service/Dockerfile
  - --context=src/retrieval_service
  - --destination=us-central1-docker.pkg.dev/$PROJECT_ID/sara-repo/retrieval-service:$SHORT_SHA
  - --cache=true

# Step 2: Build the FRONTEND Docker image
- name: 'gcr.io/kaniko-project/executor:latest'
  id: 'build-frontend'
  args:
  - --dockerfile=src/frontend_service/Dockerfile
  - --context=src/frontend_service
  - --destination=us-central1-docker.pkg.dev/$PROJECT_ID/sara-repo/frontend-service:$SHORT_SHA
  - --cache=true

# Step 3: Apply Terraform, passing BOTH new image URLs as variables
- name: 'hashicorp/terraform:1.5.7'
  id: 'terraform-apply'
  entrypoint: 'sh'
  args: 
    - -c
    - |
      terraform init
      terraform apply -auto-approve \
        -var="retrieval_container=us-central1-docker.pkg.dev/$PROJECT_ID/sara-repo/retrieval-service:$SHORT_SHA" \
        -var="frontend_container=us-central1-docker.pkg.dev/$PROJECT_ID/sara-repo/frontend-service:$SHORT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY