steps:
# Step 1: Build the backend Docker image, pointing to the nested directory
- name: 'gcr.io/kaniko-project/executor:latest'
  id: 'build-backend'
  args:
  - --dockerfile=terraform-genai-rag-main/src/retrieval_service/Dockerfile
  - --context=terraform-genai-rag-main/src/retrieval_service
  - --destination=us-central1-docker.pkg.dev/$PROJECT_ID/sara-repo/retrieval-service:$SHORT_SHA
  - --cache=true

# Step 2: Apply Terraform, first changing into the nested directory
- name: 'hashicorp/terraform:1.5.7'
  id: 'terraform-apply'
  dir: 'terraform-genai-rag-main' # This tells Terraform where to run
  entrypoint: 'sh'
  args: 
    - -c
    - |
      terraform init
      terraform apply -auto-approve -var="retrieval_container=us-central1-docker.pkg.dev/$PROJECT_ID/sara-repo/retrieval-service:$SHORT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY